# Generated by Django 4.1.7 on 2023-02-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('Can View Author', 'can_view_author')]},
        ),
    ]
